lsi: false
safe: true

source: .

title: Hack for LA
email: hello@hackforla.org
description: Can you design, write, or code? Are you an activist with an idea? You can help Los Angeles live up to its potential at Hack for LA. Everyone is welcome!

baseurl: ""
url: https://www.hackforla.org


# When/Before creating a new collections remember these two pieces of advice and ask yourself. Should you?
#    1. Collections are a great way to group related content like members of a team or talks at a conference. [https://jekyllrb.com/docs/collections/]
#    2. Collection — Will have its own page, URLs, and possibly an index page. [https://gist.github.com/akibrhast/31c7bb723d80e9efe3d28f619ef0798d]


collections:
  communities:
  credits:
  guide-pages:
    output: true
  press:
  projects:
    output: true
  sponsors:
  testimonials:

# Please refer to the documentation here[https://jekyllrb.com/docs/datafiles/] before modifying defaults
# The settings below reads as so
#     - Everything within the `pages` directory that is of type `pages` will be rendered using the `default` layout as defined ins `_layouts/default.html`
#     - Everything within the `_projects` directory that is of type `projects` will be rendered using the `project` layout as defined ins `_layouts/project.html`
#     - Everything within the `_guide-pages` directory that is of type `guide-pages` will be rendered using the `guide-pages` layout as defined ins `_layouts/guide-pages.html`
defaults:
  - scope:
      path: "pages" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_projects" # an empty string here means all files in the project
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "_guide-pages" # an empty string here means all files in the project
      type: "guide-pages"
    values:
      layout: "guide-pages"
