# This is a basic workflow that is manually triggered

name: contrib workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      owner:
        required: true
      repo:
        required: true

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let contributors = github.repos.listContributors({
              owner: `${{ github.event.inputs.owner }}`,
              repo: `${{ github.event.inputs.repo }}`,
            });
            console.log(contributors);
