# This is a basic workflow that is manually triggered

name: contrib workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      read_respository:
        owner:
          description: The owner/organization name the repository belongs to
          required: true
        repo:
          description: The name of the repository to query contributors from
          required: true
      write_repository:
        owner:
          description: The owner/organization name the repository belongs to
          required: false  
        repo:
          description: The name of the repository to query contributors from
          required: true

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let contributors = await github.repos.listContributors({
              owner: `${{ github.event.inputs.owner }}`,
              repo: `${{ github.event.inputs.repo }}`,
              per_page: 100
            });
            contributors = contributors.data
            console.log(`\`\`\`\n@${contributors.map(contributor => contributor.login).join(', @')}\n\`\`\` `);
