name: Update GitHub Data
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: false
        default: 'RastaLord'

jobs:
  github_data:
    runs-on: ubuntu-latest
    if: github.repository == 'akibrhast/hackforla'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: GitHub Action for install npm dependencies
      uses: bahmutov/npm-install@v1
      with:
        working-directory: github-actions/github-data
    
    - name: Generate github-data.json
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: npm get-project-data.js
      working-directory: github-actions/github-data

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        # Optional glob pattern of files which should be added to the commit
        file_pattern: _data/github-data.json

        commit_message: Update contributor and language data

        # Commit author settings
        commit_author: GitHub Actions Bot <hackforla-bot@hackforla.org>
